# Site settings
title: My personal website
description: A self introduction of Qinghao
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Qinghao
user_description: My personal website
user_title: Software/Robotics/
email: qinghao@mail.ustc.edu.cn
twitter_username: Carl zhuang
github_username:  zz710318
gplus_username:  Carl zhuang

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
