title:               人工智能伦理导论
url:                 https://zz710318.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              carl
  url:               zz710318.github.io
  email:             carl@mail.ustc.edu.cn

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist